package cf.tilgiz.codewars;

import java.util.Arrays;

/**
 * @author Ilgiz Tukhvatov
 */
public class SequenceSum {
    public static int[] sumOfN(int n) {
        int multiplier = (n > 0) ? 1 : -1;
        int[] result = new int[Math.abs(n) + 1];
        for (int i = 0; i <= Math.abs(n); i++) {
//            System.out.println(i);
            result[i] = multiplier * sum(i);
//            System.out.println(Arrays.toString(result));
        }
        return result; //Generated by die roll; guaranteed to be random
    }
    public static int sum(int n){
        if (n == 0) return 0;
        return n + sum(n - 1);
    }
}
